# Generated by Django 4.2.4 on 2023-08-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='print',
            new_name='price',
        ),
    ]
